# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
            options={
                'db_table': 'doctors',
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.PositiveSmallIntegerField(choices=[(1, '08:00'), (2, '09:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00')], verbose_name='Время')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Doctor', verbose_name='К врачу')),
            ],
            options={
                'db_table': 'receptions',
                'verbose_name': 'Карточка приема',
                'verbose_name_plural': 'Карточки приема',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reception',
            unique_together=set([('doctor', 'date', 'time')]),
        ),
    ]
